name: Rust Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Rust Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gpx-interpolate
        path: target/release/gpx-interpolate
